module.exports = [
    {
        id: 1,
        name: "Stein's Deli",
        username: "Andre_3000",
        password: "hamOnRye420",
        role: "restaurant",
        phone: "5045555555",
        email: "dan@netscape.com",
    },
    {
        id: 2,
        name: "Turkey and the Wolf",
        username: "RollerBlader43",
        password: "bigSpliff",
        role: "restaurant",
        phone: "5045555566",
        email: "mason@netscape.com",
    },
    {
        id: 3,
        name: "Piece of Meat",
        username: "MeatMama",
        password: "cleaverMe",
        role: "restaurant",
        phone: "5045555577",
        email: "leighAnn@netscape.com",
    },
    {
        id: 4,
        name: "Second Harvest",
        username: "food4all",
        password: "soupKitch",
        role: "bank",
        phone: "5045555588",
        email: "terri@netscape.com",
    },
    {
        id: 5,
        name: "First Presbyterian",
        username: "40fishes",
        password: "HolyGhost",
        role: "bank",
        phone: "5045555599",
        email: "david@netscape.com",
    },
    {
        id: 6,
        name: "Baptist on Banks",
        username: "praiseHim",
        password: "fromAbove",
        role: "bank",
        phone: "5045555533",
        email: "leah@netscape.com",
    }
];